# What port should the server listen on?
# This is how you will connect as a client.
port: 24833

# Cluster settings
cluster:
  # Whether or not to enable clustering
  enabled: false
  # Allow unverified clusters to connect
  allowUnverified: false
  # The maximum number of nodes to allow in the cluster
  maxNodes: 10

# Settings for how clients are authenticated
# This is the default configuration, and should be modified
# to suit your needs.
authorization:
  # Whether or not skyline should enable authorization
  enabled: true
  # Database options for authorization
  database:
      # Valid strategies include:
      # - "local" (for testing, not recommended for production)
      # - "redis" (default)
      # - "mongo"
      # - "postgres"
      provider: "redis"
      # If the strategy is "local", this is the path to the local file
      host: "file://server/credentials.env"
      # Port of the strategy
      port: 6379
      # Auth of the strategy (if any)
      # Username in the case of "postgres", "mongo", or "redis"
      username: "username"
      # Password in the case of "postgres", "mongo", or "redis"
      password: "password"
  # Token Type is the type of token to use for authorization
  # Valid types include:
  # - "skyline" (default)
  # - "jwt"
  # - "uuid"
  kind: "skyline"
  # The maximum number of attempts to try to authenticate a user
  # if this is reached, the user will be locked out for a period of time
  # and their token will expire.
  maxAttempts: 3

# Server network settings
network:
  # The type of network to use
  # Valid types include:
  # - "tcp" (default)
  # - "udp"
  mode: "tcp"
  # The maximum number of connections to allow
  # 0 means unlimited
  maxConnections: 0