[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binary_utils = { git = "https://github.com/NetrexMC/BinaryUtil.git", branch = "rewrite" }
tokio = "1.27.0"
